num = @{ int ~ ("." ~ ASCII_DIGIT*)? ~ (^"e" ~ int)? }
    int = { ("+" | "-")? ~ ASCII_DIGIT+ }

var = _{var_x | var_y}
var_x = @{ "x" }
var_y = @{ "y" }

operation = _{ add | subtract | multiply | divide | power }
    add      = { "+" }
    subtract = { "-" }
    multiply = { "*" }
    divide   = { "/" }
    power    = { "^" }

function_call = _{ sin | cos | tan }
    sin = { "sin" ~ "(" ~ expr ~ ")" }
    cos = { "cos" ~ "(" ~ expr ~ ")" }
    tan = { "tan" ~ "(" ~ expr ~ ")" }

expr = { term ~ (operation ~ term)* }
term = _{ num | var | function_call | "(" ~ expr ~ ")"}

calculation = _{ SOI ~ expr ~ EOI }

WHITESPACE = _{ " " | "\t" }